<a href="https://colab.research.google.com/github/PRAISE-KING/PythonProgramming/blob/master/ClassificationLesson1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [317]:
# Fetching data
# data analysis - understanding the data
# Machine learning
# Evaluation/Testing
# Predictions/Deployments

In [318]:
# step 1: Data Fetching

import pandas # are used for fetching and analysing data
data = pandas.read_csv("https://modcom.co.ke/data/datasets/pima.csv")
data

,Children,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,Diabetic
1,1,85,66,29,0,26.6,0.351,31,Not Diabetic
2,8,183,64,0,0,23.3,0.672,32,Diabetic
3,1,89,66,23,94,28.1,0.167,21,Not Diabetic
4,0,137,40,35,168,43.1,2.288,33,Diabetic
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,Not Diabetic
764,2,122,70,27,0,36.8,0.340,27,Not Diabetic
765,5,121,72,23,112,26.2,0.245,30,Not Diabetic
766,1,126,60,0,0,30.1,0.349,47,Diabetic
767,1,93,70,31,0,30.4,0.315,23,Not Diabetic

In [319]:
# Data analysis(though not done fully)

# checking the number of rows and collumns 
data.shape

(768, 9)

In [320]:
# Printing first ten records
data.head(10)

,Children,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,Diabetic
1,1,85,66,29,0,26.6,0.351,31,Not Diabetic
2,8,183,64,0,0,23.3,0.672,32,Diabetic
3,1,89,66,23,94,28.1,0.167,21,Not Diabetic
4,0,137,40,35,168,43.1,2.288,33,Diabetic
5,5,116,74,0,0,25.6,0.201,30,Not Diabetic
6,3,78,50,32,88,31.0,0.248,26,Diabetic
7,10,115,0,0,0,35.3,0.134,29,Not Diabetic
8,2,197,70,45,543,30.5,0.158,53,Diabetic
9,8,125,96,0,0,0.0,0.232,54,Diabetic

In [321]:
# the last ten records
data.tail(10)

,Children,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
758,1,106,76,0,0,37.5,0.197,26,Not Diabetic
759,6,190,92,0,0,35.5,0.278,66,Diabetic
760,2,88,58,26,16,28.4,0.766,22,Not Diabetic
761,9,170,74,31,0,44.0,0.403,43,Diabetic
762,9,89,62,0,0,22.5,0.142,33,Not Diabetic
763,10,101,76,48,180,32.9,0.171,63,Not Diabetic
764,2,122,70,27,0,36.8,0.340,27,Not Diabetic
765,5,121,72,23,112,26.2,0.245,30,Not Diabetic
766,1,126,60,0,0,30.1,0.349,47,Diabetic
767,1,93,70,31,0,30.4,0.315,23,Not Diabetic

In [322]:
# statistical analysis (differential statistics)
data.describe()

,Children,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000

In [323]:
# Step 3:Machine Learning
# is a process that applies scientific methods/algorithms to get hidden insights, patterns, trends from data
# Categories of machine learning

# Classification ->goal: prediction,-features and outcome, ->the outcome columns is textual(text not a number)
# -classification -group data into specified classes /groups based on their features

# Regression ->goal: prediction,-Features and outcome ->the outcome is numerical data

# Clustering

In [324]:
# grouping the whole data sets into features (X) and outcome(Y)

array = data.values

# Features
X = array[0:769, 0:8] # IF YOU WANT ALL DATA for column then [:, 0:4] or for all rows and columns [: , :] can also do for rows alone 
X

array([[6, 148, 72, ..., 33.6, 0.627, 50],
       [1, 85, 66, ..., 26.6, 0.351, 31],
       [8, 183, 64, ..., 23.3, 0.672, 32],
       ...,
       [5, 121, 72, ..., 26.2, 0.245, 30],
       [1, 126, 60, ..., 30.1, 0.349, 47],
       [1, 93, 70, ..., 30.4, 0.315, 23]], dtype=object)

In [325]:
# outcome
Y = array[: , 8]
Y

array(['Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic',
       'Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic', 'Diabetic',
       'Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Diabetic', 'Diabetic', 'Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Diabetic', 'Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic', 'Diabetic',
       'Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic', 'Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic', 'Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic', 'Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Diabetic', 'Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic',
       'Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic'],
      dtype=object)

In [326]:
X_test

array([[3, 173, 82, ..., 38.4, 2.137, 25],
       [5, 144, 82, ..., 32.0, 0.452, 58],
       [3, 174, 58, ..., 32.9, 0.593, 36],
       ...,
       [0, 165, 76, ..., 47.9, 0.259, 26],
       [2, 155, 74, ..., 26.6, 0.433, 27],
       [1, 85, 66, ..., 26.6, 0.351, 31]], dtype=object)

In [327]:
Y_test

array(['Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Diabetic', 'Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic', 'Diabetic',
       'Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Diabetic', 'Diabetic', 'Diabetic',
       'Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Diabetic', 'Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic',
       'Diabetic', 'Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Not Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Diabetic', 'Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Diabetic',
       'Not Diabetic', 'Not Diabetic', 'Not Diabetic', 'Not Diabetic',
       'Diabetic', 'Not Diabetic'], dtype=object)

In [328]:
# from IPython.utils.tempdir import NamedFileInTemporaryDirectory
# Using sklearn library

from sklearn import model_selection #model_selection used to split data into training sets(70%) and testing sets(30%)

X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=0.30, random_state=40)
# our training is 70% (0.70)
# testing sets is 30% (0.30)

# X and Y have been subdevided into four portions Namely:
# X_train, X_test, Y_train, Y_test

In [329]:
# Training phase
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

# cross validation

In [330]:
model = RandomForestClassifier()
# Modet Training - training features(X_train) with their correct outcome (Y_train)

model.fit(X_train, Y_train)

RandomForestClassifier()

In [331]:
# model evaluation/testing

predictions = model.predict(X_test)
print("the model predicted",predictions)

the model predicted ['Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic'
 'Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Diabetic'
 'Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic']

In [332]:
# correct answers

print("The correct answers :", Y_test)

The correct answers : ['Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic'
 'Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic'
 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Diabetic'
 'Diabetic' 'Diabetic' 'Not Diabetic' 'Not Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Diabetic' 'Diabetic' 'Diabetic' 'Diabetic' 'Not Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Diabetic' 'Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic'
 'Not Diabetic' 'Not Diabetic' 'Not Diabetic' 'Diabetic' 'Not Diabetic']

In [333]:
# Scientific Model Testing
# Accuracy_score
# Confusion Matrix

from sklearn.metrics import accuracy_score

print("The model accuracy is : ", accuracy_score(predictions, Y_test)*100)

The model accuracy is :  77.48917748917748

In [334]:
# predictions
data.head(3)

,Children,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,Diabetic
1,1,85,66,29,0,26.6,0.351,31,Not Diabetic
2,8,183,64,0,0,23.3,0.672,32,Diabetic

In [339]:
pima_features = [[8,130,69,25,0,31.3,0.550,20]]
disease = model.predict(pima_features)
print("You are likely to be :", disease)

if disease == "diabetic":
  print("Please visit a health facility for more consultation..")
else:
  print("you're safe of Diabetes, please continue maintaining your health diabetic life..")

You are likely to be : ['Diabetic']
you're safe of Diabetes, please continue maintaining your health diabetic life..